name: Build APK
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Set up base SDK env only (no packages here)
      - name: Set up Android SDK (env only)
        uses: android-actions/setup-android@v3

      # Manually install cmdline-tools + platform-tools + platform + build-tools
      - name: Install Android SDK packages (non-interactive)
        shell: bash
        run: |
          set -euo pipefail
          ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"
          # fall back to preinstalled sdkmanager if "latest" isn't there yet
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -x "$SDKMANAGER" ]; then
            SDKMANAGER="/usr/local/lib/android/sdk/cmdline-tools/16.0/bin/sdkmanager"
          fi
          yes | "$SDKMANAGER" --licenses || true
          # ensure latest cmdline-tools first
          yes | "$SDKMANAGER" "cmdline-tools;latest"
          # switch to the latest sdkmanager we just installed
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMANAGER" --licenses
          # install the exact packages we need (space-separated args)
          yes | "$SDKMANAGER" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace --info --no-daemon

      - name: Verify APK exists
        run: test -f app/build/outputs/apk/debug/app-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android-app/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
