name: Build & Install (self-hosted)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: [self-hosted, windows, x64, android]
    defaults:
      run:
        shell: pwsh
        working-directory: android-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            cmdline-tools;latest
            platforms;android-34
            build-tools;34.0.0

      - name: Make gradlew executable (Windows okay)
        run: git ls-files gradlew | ForEach-Object { icacls $_ /grant:r "$env:UserName:(RX)" | Out-Null }

      - name: Build debug APK
        run: .\gradlew.bat clean :app:assembleDebug --stacktrace --info --no-daemon

      - name: Verify APK path
        run: Test-Path "app\build\outputs\apk\debug\app-debug.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android-app/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Install to connected device (ADB)
        env:
          APK_PATH: ${{ github.workspace }}\android-app\app\build\outputs\apk\debug\app-debug.apk
        run: |
          $adb = "$env:ANDROID_SDK_ROOT\platform-tools\adb.exe"
          & $adb start-server
          & $adb devices
          & $adb uninstall com.seqautomotive.fbautomation 2>$null
          & $adb install -r "$env:APK_PATH"
